### ISSUE TITLE
.net core need after i install .net core already

### ISSUE THREAD

**Issue by ericvlog** [JuganD/SubtitleAttacher#1]
1st it stated my computer no install .net core , follow the link after install and setup on windows 10 pro , it also say required it.

after restart and try .net core 6.1 install ...also same problem.

**Comment by ericvlog** [comment]
okay, download the run destop app, i wrong download run console app , thanks to this wonderful tinny tools

**Comment by lyubomirhristovv** [comment]
I'm glad you liked it! Cheers!
